zharov.info/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@page')->name('index');
Route::get('publications','PublicationsController@getIndex')->name('publications');

Route::group(['middleware' => ['web']], function () {
    Route::group(['prefix' => config('artifico2.root_path'), 'middleware' => ['backend'], 'as' => 'admin.'], function () {
        Route::resource('publications', 'PublicationController');
        Route::get('/','Admin\IndexController@index');
    });
});

Route::group(['as' => 'pages.'], function () {
    Route::get('/{alias}', 'PagesController@page')
        ->name('page')
        ->where('alias', '.*');
});

zharov.info/app/Models/Publications.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Publications extends Model
{
    const TV = 1;
    const RADIO = 2;
    const PRESS = 3;

    public static $categories = [
        self::TV => array(
            'name' => 'Телепрограммы',
            'selector' => 'tv'
        ),
        self::RADIO => array(
            'name' => 'Радиоэфиры',
            'selector' => 'radio'
        ),
        self::PRESS => array(
            'name' => 'Пресса',
            'selector' => 'press'
        ),
    ];
}

zharov.info/app/Http/Controllers/Admin/PublicationController.php
<?php

namespace App\Http\Controllers;
use App\Publications;
use Illuminate\Http\Request;
class PublicationController extends Controller {


    public function __construct()
    {
        $this->middleware('permission:view pages')->only('index');
        $this->middleware('permission:create page')->only('create', 'store');
        $this->middleware('permission:edit page')->only('edit', 'update');
        $this->middleware('permission:delete page')->only('destroy');
    }


    public function index(Request $request)
    {
        return view('publications.Admin.index', [
            'publications' => Publications::Where(
                'title',
                'like',
                '%' . $request->search . '%'
            )->orderBy('date','desc')->paginate(15),
            'search' => $request->search
        ]);
    }

    public function store(Request $request)
    {

        $this->validate($request, [
            'title' => 'required',
            'title*' => 'max:255',
            'author' => 'required',
            'href' => 'required',
            'date' => 'required'

        ], [
            'title*.required'  => 'Название обязательное поле',
            'title*.max'       => 'Максимальная длина названия :max символов',
            'author.required'    => 'Автор обязательное поле для заполнения',
            'href.required'      => 'Ссылка обязательное поле для заполнения',
            'date.required' => 'Дата обязательное поле для заполнения'
        ]);

     $publication = new Publications();
     $publication->categories_id = $request['category'];
     $publication->title = $request['title'];
     $publication->author = $request['author'];
     $publication->href = $request['href'];
     $publication->date = $request['date'];
     $publication->save();

     $request->session()->flash(
         'success',
         sprintf('Публикация успешно добавлена')
        );
        return redirect()->route('admin.publications.index');
    }

    public function create() {
        return view('publications.create');
    }

    public function edit($id) {
        $sPublication = Publications::findOrFail($id);
        return view('publications.edit')->with('publications', $sPublication);
   }

    public function update(Request $request, $id){

        $publication = Publications::findOrFail($id);
        $this->validate($request, [
            'title' => 'required',
            'author' => 'required',
            'href' => 'required',
            'date' => 'required'
        ], [
            'title*.required'  => 'Название обязательное поле',
            'title*.max'       => 'Максимальная длина названия :max символов',
            'author.required'    => 'Автор обязательное поле для заполнения',
            'href.required'      => 'Ссылка обязательное поле для заполнения',
            'date.required' => 'Дата обязательное поле для заполнения'
        ]);

        $publication->categories_id = $request['category'];
        $publication->title = $request['title'];
        $publication->author = $request['author'];
        $publication->href = $request['href'];
        $publication->date = $request['date'];
        $publication->save();

        $request->session()->flash(
           'success',
           sprintf('Публикация успешно изменена')
        );

       return redirect()->route('admin.publications.index');
    }

    public function destroy(Request $request,$publication) {
        $sPublication = Publications::findOrFail($publication);
        $sPublication->delete();

        $request->session()->flash(
            'success',
            sprintf('Публикация успешно удалена')
        );
    }
}

zharov.info/app/Http/Controllers/PublicationsController.php
<?php

namespace App\Http\Controllers;
use App\Publications;
use Nutnet\Artifico2\App\Facades\AppSettings;
class PublicationsController extends Controller
{
    public function getIndex()
    {
        $allpublcations = Publications::orderBy('date','desc')->get();
        $publications = [];
        foreach ($allpublcations as $publication) {
            $publications[$publication->categories_id][] = $publication;
        }
        $phone = AppSettings::get('cms.phone');
        return view('publications.publications')->with(['publications' => $publications,'phone' => $phone]);
    }
}
?>

zharov.info/resources/views/publications/Admin/index.blade.php
@extends('artifico2::layout')
@section('title', 'Публикации')
@section('page_header', 'Публикации')
@section('content')
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <h4><i class="icon fa fa-ban"></i> Ошибка</h4>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="box box-default">
        <div class="box-body">
            <div class="row">
                <form method="get" class="form-inline" action="{{ route('admin.publications.index') }}">
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="role" class="sr-only">Название</label>
                            <input type="text" class="form-control" id="search" name="search"
                                   value="{{ $search }}" placeholder="Название или псевдоним">
                        </div>
                        <input type="submit" class="btn btn-default" value="Искать">
                        <a href="{{ route('admin.publications.index') }}" class="btn btn-default">Сбросить</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="col-xs-12">
                    @if(Auth::user()->hasPermissionTo('create publications') || Auth::user()->hasPermissionTo('*'))
                        <a href="{{ route('admin.publications.create') }}" class="btn btn-primary margin pull-right">
                            <i class="fa fa-plus"></i> Добавить</a>@endif
                </div>
            </div>
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered table-striped table-hover dataTable" role="grid" aria-describedby="example1_info">
                            <thead>
                            <tr role="row">
                                <th>Дата</th>
                                <th>Название</th>
                                <th>Источник</th>
                                <th>Ссылка</th>
                                <th>Категория</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody class="sortable">
                            {{--@if ($publications->count() < 1)--}}
                                {{--<tr>--}}
                                    {{--<td colspan="4"></td>--}}
                                {{--</tr>--}}
                            {{--@else--}}
                                {{--@endif--}}
                                @foreach ($publications as $publication)
                                    <tr role="row" class='row-link sortable-dragging' data-id="{{ $publication->id }}"
                                        data-href='{{ route('admin.publications.edit', ['id' => $publication->id]) }}'>
                                        <td>{{ $publication->date }}</td>
                                        <td>
                                            @if (count($publication->descendants) > 0)
                                                <a href="{{ route('admin.publications.index', ['id' => $publication->id]) }}">{{ $publication->title }}</a>
                                            @else
                                                {{ $publication->title }}
                                            @endif
                                        </td>
                                        <td>{{ $publication->author }}</td>
                                        <td>{{ $publication->href }}</td>
                                        <td>{{\App\Publications::$categories[$publication->categories_id]['name']}}</td>
                                        <td>
                                            <div class="btn-group">
                                                <a class="btn btn-default btn-xs"
                                                   href="{{ route('admin.publications.edit', ['id' => $publication->id]) }}"><i
                                                            class="fa fa-edit"></i></a>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            {{ $publications->links() }}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    @stop