zharov.info/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@page')->name('index');
Route::get('publications','PublicationsController@getIndex')->name('publications');

Route::group(['middleware' => ['web']], function () {
    Route::group(['prefix' => config('artifico2.root_path'), 'middleware' => ['backend'], 'as' => 'admin.'], function () {
        Route::resource('publications', 'PublicationController');
        Route::get('/','Admin\IndexController@index');
    });
});

Route::group(['as' => 'pages.'], function () {
    Route::get('/{alias}', 'PagesController@page')
        ->name('page')
        ->where('alias', '.*');
});

zharov.info/app/Models/Publications.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Publications extends Model
{
    const TV = 1;
    const RADIO = 2;
    const PRESS = 3;

    public static $categories = [
        self::TV => array(
            'name' => 'Телепрограммы',
            'selector' => 'tv'
        ),
        self::RADIO => array(
            'name' => 'Радиоэфиры',
            'selector' => 'radio'
        ),
        self::PRESS => array(
            'name' => 'Пресса',
            'selector' => 'press'
        ),
    ];
}

zharov.info/app/Http/Controllers/Admin/PublicationController.php
<?php

namespace App\Http\Controllers;
use App\Publications;
use Illuminate\Http\Request;
class PublicationController extends Controller {


    public function __construct()
    {
        $this->middleware('permission:view pages')->only('index');
        $this->middleware('permission:create page')->only('create', 'store');
        $this->middleware('permission:edit page')->only('edit', 'update');
        $this->middleware('permission:delete page')->only('destroy');
    }


    public function index(Request $request)
    {
        return view('publications.Admin.index', [
            'publications' => Publications::Where(
                'title',
                'like',
                '%' . $request->search . '%'
            )->orderBy('date','desc')->paginate(15),
            'search' => $request->search
        ]);
    }

    public function store(Request $request)
    {

        $this->validate($request, [
            'title' => 'required',
            'title*' => 'max:255',
            'author' => 'required',
            'href' => 'required',
            'date' => 'required'

        ], [
            'title*.required'  => 'Название обязательное поле',
            'title*.max'       => 'Максимальная длина названия :max символов',
            'author.required'    => 'Автор обязательное поле для заполнения',
            'href.required'      => 'Ссылка обязательное поле для заполнения',
            'date.required' => 'Дата обязательное поле для заполнения'
        ]);

     $publication = new Publications();
     $publication->categories_id = $request['category'];
     $publication->title = $request['title'];
     $publication->author = $request['author'];
     $publication->href = $request['href'];
     $publication->date = $request['date'];
     $publication->save();

     $request->session()->flash(
         'success',
         sprintf('Публикация успешно добавлена')
        );
        return redirect()->route('admin.publications.index');
    }

    public function create() {
        return view('publications.create');
    }

    public function edit($id) {
        $sPublication = Publications::findOrFail($id);
        return view('publications.edit')->with('publications', $sPublication);
   }

    public function update(Request $request, $id){

        $publication = Publications::findOrFail($id);
        $this->validate($request, [
            'title' => 'required',
            'author' => 'required',
            'href' => 'required',
            'date' => 'required'
        ], [
            'title*.required'  => 'Название обязательное поле',
            'title*.max'       => 'Максимальная длина названия :max символов',
            'author.required'    => 'Автор обязательное поле для заполнения',
            'href.required'      => 'Ссылка обязательное поле для заполнения',
            'date.required' => 'Дата обязательное поле для заполнения'
        ]);

        $publication->categories_id = $request['category'];
        $publication->title = $request['title'];
        $publication->author = $request['author'];
        $publication->href = $request['href'];
        $publication->date = $request['date'];
        $publication->save();

        $request->session()->flash(
           'success',
           sprintf('Публикация успешно изменена')
        );

       return redirect()->route('admin.publications.index');
    }

    public function destroy(Request $request,$publication) {
        $sPublication = Publications::findOrFail($publication);
        $sPublication->delete();

        $request->session()->flash(
            'success',
            sprintf('Публикация успешно удалена')
        );
    }
}

zharov.info/app/Http/Controllers/PublicationsController.php
<?php

namespace App\Http\Controllers;
use App\Publications;
use Nutnet\Artifico2\App\Facades\AppSettings;
class PublicationsController extends Controller
{
    public function getIndex()
    {
        $allpublcations = Publications::orderBy('date','desc')->get();
        $publications = [];
        foreach ($allpublcations as $publication) {
            $publications[$publication->categories_id][] = $publication;
        }
        $phone = AppSettings::get('cms.phone');
        return view('publications.publications')->with(['publications' => $publications,'phone' => $phone]);
    }
}
?>

zharov.info/resources/views/publications/create.blade.php
@extends('artifico2::layout')
@section('title', 'Добавить публикацию')
@section('page_header', 'Добавить публикацию')
@section('content')

@section('breadcrumbs')
    <ol class="breadcrumb">
        <li><a href="{{ config('artifico2.root_path') }}"><i class="fa fa-dashboard"></i> Главная</a></li>
        <li><a href="{{ route('admin.publications.index') }}">Публикации</a></li>
    </ol>
@endsection

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <h4><i class="icon fa fa-ban"></i> Ошибка</h4>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form method="post" action="{{ route('admin.publications.store') }}">
        {{ csrf_field() }}
        <div class="box box-default">
            <div class="box-body">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group {{ $errors->has('date') ? 'has-error' : '' }}">
                            <label for="date">Дата</label>
                            <input type='date' id="date" class="form-control" name="date" />
                            @if ($errors->has('date'))
                                {!! $errors->first('date','<span class="help-block">:message</span>')  !!}
                            @endif
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                            <label for="title">Название</label>
                            <br>
                            <input type="text" class="form-control" name="title" id="title"  value="{{old('title')}}">
                            @if ($errors->has('title'))
                                {!! $errors->first('title','<span class="help-block">:message</span>')  !!}
                            @endif
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group {{ $errors->has('author') ? 'has-error' : '' }}">
                            <label for="author">Источник</label>
                            <br>
                            <input type="text" class="form-control" name="author" id="author" value="{{old('author')}}">
                            @if ($errors->has('author'))
                                {!! $errors->first('author','<span class="help-block">:message</span>')  !!}
                            @endif
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group {{ $errors->has('href') ? 'has-error' : '' }}">
                            <label for="href">Ссылка</label>
                            <br>
                            <input type="text" class="form-control" name="href" id="href" value="{{old('href')}}">
                            @if ($errors->has('href'))
                                {!! $errors->first('href','<span class="help-block">:message</span>')  !!}
                            @endif
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="active">Категория</label>
                            <select name="category" id="category" class="form-control">
                                @foreach( \App\Publications::$categories as $categoryID => $category)
                                    <option value="{{$categoryID}}">{{$category['name']}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
         </div>
        <div class="form-group">
            @if(Auth::user()->hasPermissionTo('create publications') || Auth::user()->hasPermissionTo('*'))
                <input type = "submit" value="Сохранить" class = "btn btn-success" style="min-width:100px;">
            @endif
            <a href="{{ route('admin.publications.index') }}" class="btn btn-default"
               style="min-width:100px;">Отмена</a>
        </div>

    </form>

@stop

zharov.info/resources/views/publications/edit.blade.php
@extends('artifico2::layout')
@section('title', 'Редактировать публикацию')
@section('page_header', 'Редактировать публикацию')
@section('content')
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <h4><i class="icon fa fa-ban"></i> Ошибка</h4>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form method="post" action="{{ route('admin.publications.update',['id'=>$publications->id]) }}">
        {{ method_field('PUT') }}
        {{ csrf_field() }}
        <div class="box">
            <div class="box-body">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group {{$errors->has('date') ? 'has-error' : ''}}">
                            <label for="date">Дата</label>
                            <input type='date' id="date" class="form-control" name="date" value="{{$publications->date}}" />
                            @if ($errors->has('date'))
                                {!! $errors->first('date','<span class="help-block">:message</span>')  !!}
                            @endif
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                            <label for="title">Название</label>
                            <br>
                            <input type="text" class="form-control" name="title" id="title" value="{{$publications->title}}">
                            @if ($errors->has('title'))
                                {!! $errors->first('title','<span class="help-block">:message</span>')  !!}
                            @endif
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group {{ $errors->has('author') ? 'has-error' : '' }}">
                            <label for="author">Источник</label>
                            <br>
                            <input type="text" class="form-control" name="author" id="author" value="{{$publications->author}}">
                            @if ($errors->has('author'))
                                {!! $errors->first('author','<span class="help-block">:message</span>')  !!}
                            @endif
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group {{ $errors->has('href') ? 'has-error' : '' }}">
                            <label for="href">Ссылка</label>
                            <br>
                            <input type="text" class="form-control" name="href" id="href" value="{{$publications->href}}">
                            @if ($errors->has('href'))
                                {!! $errors->first('href','<span class="help-block">:message</span>')  !!}
                            @endif
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label for="active">Категория</label>
                            <select name="category" id="category" class="form-control">
                                @foreach( \App\Publications::$categories as $categoryID => $category)
                                    <option {{ $publications->categories_id === $categoryID ? 'selected' : '' }} value="{{$categoryID}}">{{$category['name']}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            @if(Auth::user()->hasPermissionTo('edit publications') || Auth::user()->hasPermissionTo('*'))
                <input type = "submit" class = "btn btn-success" value="Сохранить" style="min-width:100px;">
            @endif
            <a href="{{ route('admin.publications.index') }}" class="btn btn-default"
               style="min-width:100px;">Отмена</a>
            @if(Auth::user()->hasPermissionTo('delete publications') || Auth::user()->hasPermissionTo('*'))
                <button type="button" class="destroy-model btn btn-default pull-right"
                        data-href="<?php echo e(route('admin.publications.destroy', ['id' => $publications->id])); ?>"
                        data-redirect="<?php echo e(route('admin.publications.index')); ?>"
                        id="destroy-model-accept">Удалить</button>
            @endif
        </div>
        <input type="hidden" name="publication_id" value="{{$publications->id}}">
    </form>


@stop

zharov.info/resources/views/publications/publications.blade.php
@extends('layouts.main')
@section('meta_title', 'Публикации – Адвокат Жаров')
@section('meta_description','Архив телепередач, статей и радио эфиров с участием адвоката Жарова.')
@section('content')
<main class="content">
    <main class="content__wrapper">
        <h1 class="content__title">Публикации</h1>
        <div id="content__anchors-block-id" class="content__anchors-block">
            @foreach($publications as $categoryID => $categoryPublications)
                <a href="#{{App\Publications::$categories[$categoryID]['selector']}}" class="content__link">{{App\Publications::$categories[$categoryID]['name']}}</a>
            @endforeach
        </div>
        <div class="content__blocks">
            @if (!$publications)
                <p>Нет публикаций</p>
            @endif
            @foreach($publications as $categoryID => $categoryPublications)
            <div class="content__block content__block--publications">
                <h2 id="{{App\Publications::$categories[$categoryID]['selector']}}" class="content__block-title">{{App\Publications::$categories[$categoryID]['name']}}</h2>
                            @foreach($categoryPublications as $publicationID => $publication )
                            <div class="content__show-block"><a href="{{$publication->href}}" target="_blank" class="content__show-name">{{$publication->title}}</a>
                                <p class="content__show-time">{{\Carbon\Carbon::parse($publication->date)->format('d.m.Y')}} {{$publication->author}}</p>
                            </div>
                            @endforeach
                @if(count($categoryPublications)>5)
                <div class="content__link content__link--publications content__show-all content__show-all--tv">
                    <p class="content__show-all-link">Показать все</p>
                </div>
                @endif
            </div>
@endforeach
        </div>
    </main>
@endsection